using FinancialTrackingSimulator.Model;

public class StockPriceService
{
    private readonly Dictionary<int, Stock> _stockData;
    private readonly Random _random;
    private readonly Timer _timer;
    public event Action OnPricesUpdated; // This will notify the UI to refresh when prices update

    // Event to notify when a specific stock is updated
    public event Action<Stock> StockUpdated;

    public StockPriceService()
    {
        _random = new Random();

        // Initialize in-memory stock data with all provided stocks
        _stockData = new Dictionary<int, Stock>
        {{ 1, new Stock { Id = 1, Name = "Apple Inc. (AAPL)", Price = 175.45m, DailyChange = 1.50m, OtherInformation = "Apple Inc. is a leading global technology company known for its innovative consumer electronics, software, and services. Founded in 1976 by Steve Jobs, Steve Wozniak, and Ronald Wayne, Apple revolutionized the personal computer market with its Macintosh computers and later transformed the mobile phone industry with the iPhone. Over the years, Apple has expanded its product line to include iPads, Apple Watches, and services like the App Store, Apple Music, and iCloud. Today, Apple is one of the most valuable companies in the world, with a market capitalization exceeding $2 trillion. Its products are highly regarded for their design, user experience, and ecosystem integration, making it a dominant force in the tech industry." }},
            { 2, new Stock { Id = 2, Name = "Microsoft Corp. (MSFT)", Price = 330.12m, DailyChange = -0.75m, OtherInformation = "Microsoft Corporation is a multinational technology company founded by Bill Gates and Paul Allen in 1975. It is best known for developing and selling computer software, notably the Windows operating system and the Microsoft Office Suite. Microsoft has diversified its portfolio over the years by entering the gaming industry with Xbox, acquiring LinkedIn, and expanding into cloud computing through Azure. Azure has become a major competitor to Amazon Web Services (AWS) in cloud infrastructure. Microsoft’s growth has been driven by its ability to adapt to new market demands while maintaining dominance in its core software business. With a market cap over $2 trillion, it remains a pivotal player in tech." }},
            { 3, new Stock { Id = 3, Name = "Tesla Inc. (TSLA)", Price = 880.24m, DailyChange = 12.36m, OtherInformation = "Tesla Inc., founded in 2003 by Martin Eberhard and Marc Tarpenning, later led by Elon Musk, is a pioneer in electric vehicles (EVs) and clean energy solutions. The company has disrupted the automotive industry with its innovative electric cars, including the Model S, Model 3, Model X, and Model Y. Tesla’s mission is to accelerate the world’s transition to sustainable energy, and it also focuses on energy storage products like the Powerwall and solar energy solutions. With a rapidly growing network of superchargers and advancements in autonomous driving technology, Tesla has positioned itself as a leader in the EV market, with ambitious goals for the future." }},
            { 4, new Stock { Id = 4, Name = "Amazon.com Inc. (AMZN)", Price = 145.36m, DailyChange = 2.25m, OtherInformation = "Amazon.com Inc. was founded by Jeff Bezos in 1994 as an online bookstore, but it quickly grew into the world’s largest e-commerce platform. Today, Amazon offers an extensive range of products and services, from electronics and groceries to digital content and cloud computing through its subsidiary, Amazon Web Services (AWS). AWS is a significant driver of Amazon’s profitability, providing cloud infrastructure and solutions to businesses worldwide. Over the years, Amazon has expanded into new areas, including smart devices with Alexa, logistics with Amazon Prime, and media with Prime Video. Amazon’s influence extends across numerous industries, making it a key player in global commerce and technology." }},
            { 5, new Stock { Id = 5, Name = "Alphabet Inc. (GOOGL)", Price = 140.78m, DailyChange = 1.89m, OtherInformation = "Alphabet Inc. is the parent company of Google, which was founded by Larry Page and Sergey Brin in 1998. Alphabet was created in 2015 to restructure Google’s various ventures, separating its core businesses like search, YouTube, and advertising from its experimental projects, known as Other Bets. Google remains the dominant force in online search, digital advertising, and mobile software through its Android operating system. Alphabet’s investments in autonomous vehicles (Waymo), healthcare (Verily), and artificial intelligence have positioned it as a leader in innovation. Alphabet’s ability to generate revenue through diverse channels has made it one of the most valuable companies in the world." }},
            { 6, new Stock { Id = 6, Name = "NVIDIA Corp. (NVDA)", Price = 450.20m, DailyChange = -5.60m, OtherInformation = "NVIDIA Corporation, founded in 1993 by Jensen Huang, Chris Malachowsky, and Curtis Priem, is a leading designer of graphics processing units (GPUs) for gaming, data centers, and artificial intelligence. NVIDIA’s GPUs are known for their high performance, making them a popular choice among gamers and professionals. In recent years, NVIDIA has expanded its reach into AI and machine learning, developing platforms like CUDA and acquiring Mellanox to enhance its data center capabilities. NVIDIA’s innovations have positioned it as a critical player in the gaming industry and a key enabler of AI advancements, making it one of the most influential semiconductor companies." }},
            { 7, new Stock { Id = 7, Name = "Meta Platforms Inc. (META)", Price = 270.14m, DailyChange = 3.45m, OtherInformation = "Meta Platforms Inc., formerly known as Facebook, was founded by Mark Zuckerberg in 2004. The company started as a social networking site but has grown into a global technology conglomerate with a focus on social media, messaging, and virtual reality. Meta owns several popular platforms, including Facebook, Instagram, WhatsApp, and Oculus. The rebranding to Meta in 2021 signaled the company’s ambition to build the metaverse, a virtual space where users can interact, work, and play. Despite facing challenges around data privacy and regulation, Meta remains one of the most influential companies in digital media and communication." }},
            { 8, new Stock { Id = 8, Name = "Johnson & Johnson (JNJ)", Price = 162.50m, DailyChange = 0.50m, OtherInformation = "Johnson & Johnson, founded in 1886, is a multinational corporation specializing in pharmaceuticals, medical devices, and consumer health products. The company is known for its innovative contributions to healthcare, including lifesaving drugs, surgical devices, and consumer products like baby care and Band-Aid. Johnson & Johnson’s commitment to research and development has made it a leader in the healthcare industry. Over the years, it has developed a broad portfolio of products that address major medical needs. Despite facing legal challenges in recent years, Johnson & Johnson remains a trusted brand in healthcare with a global presence in over 175 countries." }},
            { 9, new Stock { Id = 9, Name = "Procter & Gamble Co. (PG)", Price = 146.78m, DailyChange = -0.65m, OtherInformation = "Procter & Gamble Co. (P&G) is a global consumer goods company founded in 1837 by William Procter and James Gamble. It is one of the largest and most respected manufacturers of household products, including brands like Tide, Gillette, Pampers, and Crest. P&G’s focus on product innovation, quality, and brand recognition has helped it maintain market leadership in several categories. The company’s commitment to sustainability and social responsibility is reflected in its efforts to reduce its environmental footprint and improve the quality of life for consumers. P&G’s broad portfolio and strong brand loyalty make it a cornerstone of the consumer goods industry." }},
            { 10, new Stock { Id = 10, Name = "Visa Inc. (V)", Price = 236.44m, DailyChange = 1.15m, OtherInformation = "Visa Inc. is a global payments technology company that facilitates electronic funds transfers through its extensive network of credit, debit, and prepaid cards. Founded in 1958 as BankAmericard, Visa has grown into one of the world’s largest payment processing companies. Visa’s infrastructure supports secure and reliable transactions, enabling millions of businesses and consumers to transact seamlessly. With the rise of digital and mobile payments, Visa has continued to innovate, investing in new technologies to enhance the user experience and expand its reach. Today, Visa operates in more than 200 countries and territories, processing billions of transactions annually." }},
            { 11, new Stock { Id = 11, Name = "Coca-Cola Co. (KO)", Price = 58.91m, DailyChange = 0.45m, OtherInformation = "The Coca-Cola Company is the world's largest beverage company, best known for its flagship product, Coca-Cola. Founded in 1886 by John Stith Pemberton, Coca-Cola has since grown into a global powerhouse with a diverse portfolio of beverages, including carbonated soft drinks, fruit juices, bottled water, energy drinks, and teas. The company operates in more than 200 countries and offers over 500 brands, with some of its most popular products being Sprite, Fanta, and Minute Maid. Coca-Cola has built a strong brand image through innovative marketing campaigns and sponsorships, including partnerships with global sports events like the Olympics and FIFA World Cup. It remains a leader in the beverage industry and a symbol of American culture." }},
            { 12, new Stock { Id = 12, Name = "PepsiCo Inc. (PEP)", Price = 174.25m, DailyChange = -0.23m, OtherInformation = "PepsiCo Inc. is a global leader in the food and beverage industry, known for its iconic Pepsi-Cola brand. Founded in 1965 through the merger of Pepsi-Cola and Frito-Lay, the company has expanded its portfolio to include a wide range of snacks, beverages, and packaged foods. Key brands under PepsiCo include Mountain Dew, Lay's, Gatorade, Tropicana, Quaker, and Doritos. The company operates in over 200 countries and focuses on product innovation, sustainability, and consumer health. PepsiCo’s efforts to reduce sugar content, invest in healthier snacks, and promote eco-friendly practices have positioned it as a forward-thinking player in the global market." }},
            { 13, new Stock { Id = 13, Name = "Walmart Inc. (WMT)", Price = 159.23m, DailyChange = 0.80m, OtherInformation = "Walmart Inc. is the world's largest retailer, offering a wide variety of products ranging from groceries and electronics to apparel and home goods. Founded in 1962 by Sam Walton, Walmart has grown into a global retail giant with more than 11,000 stores across 27 countries. The company is known for its commitment to low prices, which it achieves through economies of scale and an efficient supply chain. Walmart’s success in e-commerce, particularly with Walmart+, its subscription service, has strengthened its position in the digital age. The company’s focus on sustainability and community support continues to shape its identity as a leader in the retail industry." }},
            { 14, new Stock { Id = 14, Name = "Berkshire Hathaway Inc. (BRK.A)", Price = 541.00m, DailyChange = 215.00m, OtherInformation = "Berkshire Hathaway Inc. is a diversified multinational conglomerate led by Warren Buffett, one of the most successful investors in history. Originally a textile company, Berkshire Hathaway was transformed by Buffett into a holding company with investments in various sectors, including insurance, utilities, railroads, and consumer goods. Notable subsidiaries and investments include GEICO, BNSF Railway, Dairy Queen, and significant stakes in companies like Apple, Coca-Cola, and American Express. Buffett’s value investing philosophy has guided the company’s growth, making it one of the largest and most respected firms in the world. Berkshire Hathaway's annual shareholder meeting is often referred to as the 'Woodstock of Capitalism.'" }},
            { 15, new Stock { Id = 15, Name = "Exxon Mobil Corp. (XOM)", Price = 113.27m, DailyChange = -1.50m, OtherInformation = "Exxon Mobil Corporation is one of the world’s largest publicly traded oil and gas companies, with roots tracing back to John D. Rockefeller’s Standard Oil Company. Formed through the merger of Exxon and Mobil in 1999, ExxonMobil operates in all segments of the energy industry, including exploration, production, refining, and chemicals. The company is a leader in the development of new technologies to improve efficiency and reduce environmental impact, with ongoing investments in renewable energy and carbon capture. Despite facing challenges from fluctuating oil prices and global regulations, ExxonMobil remains a dominant player in the energy sector with a significant global presence." }},
            { 16, new Stock { Id = 16, Name = "Pfizer Inc. (PFE)", Price = 32.14m, DailyChange = 0.12m, OtherInformation = "Pfizer Inc. is a leading pharmaceutical company known for developing and manufacturing innovative medicines and vaccines. Founded in 1849 by Charles Pfizer and Charles Erhart, the company has grown into one of the largest biopharmaceutical companies in the world. Pfizer is renowned for its research and development efforts, particularly in the areas of oncology, immunology, cardiology, and vaccines. The company’s partnership with BioNTech led to the development of one of the first COVID-19 vaccines, which played a crucial role in the global pandemic response. Pfizer continues to focus on advancing healthcare through new therapies and expanding access to essential medicines." }},
            { 17, new Stock { Id = 17, Name = "Intel Corp. (INTC)", Price = 38.89m, DailyChange = 0.80m, OtherInformation = "Intel Corporation, founded in 1968 by Robert Noyce and Gordon Moore, is a leading semiconductor company known for its microprocessors and technology solutions. Intel’s processors are widely used in personal computers, servers, and embedded devices, making it a key player in the technology industry. The company has been at the forefront of innovation, introducing technologies like the x86 architecture and advancements in integrated circuit design. Intel is also investing in artificial intelligence, autonomous driving, and 5G technology to expand its influence in emerging markets. With a commitment to sustainable practices and technological excellence, Intel continues to shape the future of computing." }},
            { 18, new Stock { Id = 18, Name = "Cisco Systems Inc. (CSCO)", Price = 55.23m, DailyChange = -0.42m, OtherInformation = "Cisco Systems Inc. is a leading networking hardware and software company that designs and manufactures Internet Protocol (IP)-based networking solutions. Founded in 1984 by Leonard Bosack and Sandy Lerner, Cisco revolutionized networking with its routers and switches, enabling the growth of the internet. Over the years, Cisco has expanded its portfolio to include cybersecurity, cloud solutions, and collaboration tools like Webex. The company’s products and services are essential for connecting businesses, governments, and individuals around the world. Cisco’s commitment to innovation and security has solidified its position as a global leader in networking technology." }},
            { 19, new Stock { Id = 19, Name = "Netflix Inc. (NFLX)", Price = 434.56m, DailyChange = -3.45m, OtherInformation = "Netflix Inc. is a leading streaming entertainment service, offering a vast library of movies, TV shows, and original content to subscribers around the world. Founded in 1997 by Reed Hastings and Marc Randolph, Netflix initially operated as a DVD rental service before transitioning to streaming in 2007. The company’s original productions, such as 'Stranger Things,' 'The Crown,' and 'Narcos,' have earned critical acclaim and widespread popularity. Netflix’s data-driven approach to content creation and its commitment to global expansion have helped it become a dominant force in the entertainment industry. The company continues to invest heavily in original programming and new markets." }},
            { 20, new Stock { Id = 20, Name = "JPMorgan Chase & Co. (JPM)", Price = 145.99m, DailyChange = 1.10m, OtherInformation = "JPMorgan Chase & Co. is the largest bank in the United States by assets and a leading global financial services firm. Formed through the merger of J.P. Morgan & Co. and Chase Manhattan Bank in 2000, the company has a history dating back to the 19th century. JPMorgan Chase provides a wide range of financial services, including investment banking, commercial banking, asset management, and consumer banking. Under the leadership of CEO Jamie Dimon, the company has navigated economic challenges while continuing to grow its market share. JPMorgan Chase’s commitment to digital transformation and innovation has solidified its position as a leader in the financial sector." }},
            { 21, new Stock { Id = 21, Name = "The Walt Disney Co. (DIS)", Price = 88.54m, DailyChange = 1.05m, OtherInformation = "The Walt Disney Company, founded in 1923 by Walt and Roy Disney, is a diversified international entertainment conglomerate. It is renowned for its iconic animated films, television networks, and theme parks such as Disneyland and Walt Disney World. Over the years, Disney has expanded through acquisitions of companies like Pixar, Marvel, Lucasfilm, and 21st Century Fox, cementing its position in the film and media industry. Disney also owns streaming services like Disney+, which offers a vast library of movies, series, and exclusive content. The company's long history of creativity, innovation, and brand recognition makes it a major player in global entertainment." }},
            { 22, new Stock { Id = 22, Name = "Boeing Co. (BA)", Price = 195.50m, DailyChange = -0.78m, OtherInformation = "The Boeing Company, founded in 1916, is a leading aerospace and defense company. It designs, manufactures, and sells airplanes, rotorcraft, rockets, satellites, and telecommunications equipment. Boeing is well known for its commercial aircraft, including the 737, 747, 787 Dreamliner, and military products such as the Apache helicopter and F/A-18 Super Hornet. The company is one of the largest aerospace companies in the world and a key player in the defense industry. Despite facing challenges like the 737 MAX crisis, Boeing remains integral to global aviation and innovation." }},
            { 23, new Stock { Id = 23, Name = "McDonald’s Corp. (MCD)", Price = 232.70m, DailyChange = 0.60m, OtherInformation = "McDonald’s Corporation is the world’s largest fast-food restaurant chain, known for its burgers, fries, and signature Big Mac. Founded in 1940 by Richard and Maurice McDonald, it revolutionized the industry with the concept of fast and efficient service. McDonald’s now operates over 39,000 locations in more than 100 countries. The company has adapted to changing consumer preferences by diversifying its menu and focusing on healthier options. Its strong global brand and commitment to quality have made McDonald’s a leader in the fast-food industry." }},
            { 24, new Stock { Id = 24, Name = "General Electric Co. (GE)", Price = 98.10m, DailyChange = -1.20m, OtherInformation = "General Electric Company (GE) is an American multinational conglomerate founded by Thomas Edison in 1892. GE operates in various industries, including aviation, healthcare, renewable energy, and power. Known for its history of innovation, GE has been a pioneer in electrical and technological advancements. The company’s recent restructuring focuses on core segments like aviation and healthcare while divesting non-core businesses. Despite challenges, GE remains a major player in its industries, known for its technological prowess and legacy of innovation." }},
            { 25, new Stock { Id = 25, Name = "IBM Corp. (IBM)", Price = 132.60m, DailyChange = -0.50m, OtherInformation = "International Business Machines Corporation (IBM), founded in 1911, is a multinational technology company specializing in hardware, software, and IT services. Known as 'Big Blue,' IBM was a dominant force in mainframe computing and has played a pivotal role in the development of modern computing technology. Today, IBM focuses on cloud computing, artificial intelligence with its Watson platform, and enterprise services. The company’s commitment to innovation and business solutions has positioned it as a key player in the global tech industry." }},
            { 26, new Stock { Id = 26, Name = "AT&T Inc. (T)", Price = 14.98m, DailyChange = -0.20m, OtherInformation = "AT&T Inc., one of the world’s largest telecommunications companies, traces its origins back to Alexander Graham Bell’s invention of the telephone. Today, AT&T offers a wide range of services, including wireless communication, broadband, and digital TV. The company’s acquisition of Time Warner in 2018 expanded its media and entertainment portfolio, making it a major player in the media industry. Despite divesting some assets to reduce debt, AT&T remains committed to providing innovative communication services and expanding its 5G network." }},
            { 27, new Stock { Id = 27, Name = "3M Co. (MMM)", Price = 98.70m, DailyChange = 0.65m, OtherInformation = "3M Company, founded in 1902, is a multinational conglomerate known for its innovative products in various sectors, including industrial, healthcare, consumer goods, and safety. 3M’s iconic brands include Scotch Tape, Post-it Notes, and N95 respirators. The company’s commitment to research and development has driven its growth and ability to create solutions that improve lives. 3M operates in over 70 countries and continues to focus on sustainability and product innovation to maintain its market leadership." }},
            { 28, new Stock { Id = 28, Name = "American Express Co. (AXP)", Price = 162.40m, DailyChange = 1.35m, OtherInformation = "American Express Company (Amex), founded in 1850, is a global financial services corporation known for its credit cards, charge cards, and traveler’s checks. The company has built a reputation for providing premium services and customer rewards programs. American Express serves a broad range of consumers, businesses, and merchants worldwide, focusing on convenience and security in financial transactions. Its strong brand and innovative financial products have made it a leading player in the payment card industry." }},
            { 29, new Stock { Id = 29, Name = "Starbucks Corp. (SBUX)", Price = 102.30m, DailyChange = -0.35m, OtherInformation = "Starbucks Corporation, founded in 1971 in Seattle, is a multinational coffeehouse chain known for its high-quality coffee, specialty drinks, and customer-centric experience. With over 33,000 locations globally, Starbucks has transformed the coffee culture, creating a 'third place' between work and home for its customers. The company’s commitment to ethical sourcing, sustainability, and community involvement has made it a leader in the coffee industry. Starbucks continues to innovate with new products and expand its digital offerings to enhance the customer experience." }},
            { 30, new Stock { Id = 30, Name = "Goldman Sachs Group Inc. (GS)", Price = 325.40m, DailyChange = 2.05m, OtherInformation = "The Goldman Sachs Group, Inc., founded in 1869, is a leading global investment banking, securities, and investment management firm. Goldman Sachs provides a range of financial services to corporations, financial institutions, governments, and individuals. The firm is renowned for its expertise in investment banking, asset management, and securities trading. Goldman Sachs has a strong global presence and is known for its influential role in shaping financial markets and the broader economy." }},
            { 31, new Stock { Id = 31, Name = "UnitedHealth Group Inc. (UNH)", Price = 520.12m, DailyChange = 3.23m, OtherInformation = "UnitedHealth Group is a diversified healthcare company and the largest health insurer in the United States. Founded in 1977, the company operates two primary businesses: UnitedHealthcare, which provides health benefits, and Optum, which offers health services through technology and information. UnitedHealth Group plays a key role in the American healthcare system, providing coverage to millions of people and offering innovative solutions to enhance healthcare delivery and efficiency. The company’s commitment to using data and technology to improve health outcomes has positioned it as a leader in the healthcare sector." }},
            { 32, new Stock { Id = 32, Name = "Salesforce Inc. (CRM)", Price = 256.34m, DailyChange = 1.88m, OtherInformation = "Salesforce Inc. is a leading customer relationship management (CRM) software company, founded by Marc Benioff in 1999. The company revolutionized the software industry by pioneering the software-as-a-service (SaaS) model, enabling businesses to manage customer interactions, sales, and marketing through cloud-based applications. Salesforce’s platform includes various products like Sales Cloud, Service Cloud, and Marketing Cloud. The company has expanded its capabilities through acquisitions such as Slack and Tableau, making it a key player in enterprise software and digital transformation." }},
            { 33, new Stock { Id = 33, Name = "The Home Depot Inc. (HD)", Price = 290.14m, DailyChange = 0.65m, OtherInformation = "The Home Depot Inc., founded in 1978, is the largest home improvement retailer in the United States. The company offers a wide range of products, including building materials, tools, appliances, and garden supplies. With over 2,300 stores, Home Depot serves professional contractors and do-it-yourself customers. The company’s commitment to customer service, product quality, and community involvement has made it a trusted brand in the home improvement industry. Home Depot continues to invest in e-commerce and supply chain improvements to enhance the customer experience." }},
            { 34, new Stock { Id = 34, Name = "Chevron Corp. (CVX)", Price = 163.24m, DailyChange = 1.02m, OtherInformation = "Chevron Corporation is a leading integrated energy company, involved in every aspect of the oil and gas industry. Founded in 1879 as Pacific Coast Oil Company, Chevron has grown to become one of the world’s largest energy companies. It engages in the exploration, production, refining, and marketing of oil and natural gas. Chevron is also investing in renewable energy and carbon capture technologies to address climate change and transition to a low-carbon future. The company’s global presence and diversified portfolio make it a significant player in the energy sector." }},
            { 35, new Stock { Id = 35, Name = "Abbott Laboratories (ABT)", Price = 105.12m, DailyChange = 0.45m, OtherInformation = "Abbott Laboratories, founded in 1888, is a global healthcare company that develops and manufactures medical devices, diagnostics, nutrition products, and branded generic medicines. The company’s innovative products include glucose monitoring systems, heart stents, and nutritional supplements like Ensure and Similac. Abbott is committed to improving the quality of life for people around the world through its diverse product portfolio. Its focus on innovation, research, and accessibility has made Abbott a trusted name in healthcare." }},
            { 36, new Stock { Id = 36, Name = "Adobe Inc. (ADBE)", Price = 603.98m, DailyChange = 1.74m, OtherInformation = "Adobe Inc. is a leading software company known for its creative software products, such as Photoshop, Illustrator, and Premiere Pro. Founded in 1982, Adobe has been at the forefront of digital media and content creation. The company’s cloud-based solutions, including Adobe Creative Cloud, Document Cloud, and Experience Cloud, have revolutionized how people create, manage, and share digital content. Adobe’s commitment to innovation and empowering creativity has solidified its position as a leader in the software industry." }},
            { 37, new Stock { Id = 37, Name = "Nextera Energy Inc. (NEE)", Price = 79.21m, DailyChange = -0.34m, OtherInformation = "NextEra Energy, Inc. is a leading clean energy company and the largest electric utility in the United States by market capitalization. The company operates through its two main subsidiaries: Florida Power & Light Company (FPL) and NextEra Energy Resources. NextEra is known for its investments in renewable energy, including wind and solar power, and has been a key driver of the transition to a low-carbon energy future. The company’s commitment to sustainability and innovation in energy production has positioned it as a leader in the utility sector." }},
            { 38, new Stock { Id = 38, Name = "Lockheed Martin Corp. (LMT)", Price = 383.67m, DailyChange = -0.54m, OtherInformation = "Lockheed Martin Corporation is a leading global aerospace and defense company, known for its advanced technology and innovation. The company was formed in 1995 through the merger of Lockheed Corporation and Martin Marietta. Lockheed Martin designs and manufactures a wide range of products, including fighter jets like the F-35, missiles, satellites, and defense systems. The company’s expertise in aerospace, defense, and security makes it a critical partner to governments and organizations around the world." }},
            { 39, new Stock { Id = 39, Name = "Caterpillar Inc. (CAT)", Price = 209.50m, DailyChange = 0.70m, OtherInformation = "Caterpillar Inc. is the world’s leading manufacturer of construction and mining equipment, diesel and natural gas engines, and industrial gas turbines. Founded in 1925, the company is known for its iconic yellow machines and commitment to quality and innovation. Caterpillar serves various industries, including construction, mining, oil and gas, and energy. The company’s focus on sustainable solutions and technology-driven products has made it a key player in the heavy equipment industry." }},
            { 40, new Stock { Id = 40, Name = "Bristol-Myers Squibb Co. (BMY)", Price = 62.35m, DailyChange = 0.25m, OtherInformation = "Bristol-Myers Squibb Company is a global biopharmaceutical company that discovers, develops, and delivers innovative medicines to treat serious diseases. Founded in 1858, the company has a long history of research and development in areas such as oncology, immunology, cardiovascular, and fibrosis. Bristol-Myers Squibb’s commitment to scientific innovation and improving patient outcomes has made it a leader in the pharmaceutical industry. The company continues to focus on advancing new therapies to address unmet medical needs." }},
            { 41, new Stock { Id = 41, Name = "Texas Instruments Inc. (TXN)", Price = 175.89m, DailyChange = 0.58m, OtherInformation = "Texas Instruments Incorporated (TI) is a leading semiconductor company known for its analog and embedded processing products. Founded in 1930, TI is one of the oldest and most established players in the semiconductor industry. The company’s products are used in a wide range of applications, including automotive, industrial, and consumer electronics. Texas Instruments’ focus on innovation, manufacturing excellence, and customer support has made it a key player in the semiconductor market." }},
            { 42, new Stock { Id = 42, Name = "Verizon Communications Inc. (VZ)", Price = 51.23m, DailyChange = -0.12m, OtherInformation = "Verizon Communications Inc. is one of the largest telecommunications companies in the United States. Formed in 2000 through the merger of Bell Atlantic and GTE, Verizon provides wireless, broadband, and digital TV services to millions of customers. The company is a leader in 5G network deployment, offering advanced connectivity solutions for consumers and businesses. Verizon’s commitment to network quality and customer service has positioned it as a major player in the telecommunications industry." }},
            { 43, new Stock { Id = 43, Name = "Merck & Co. Inc. (MRK)", Price = 86.50m, DailyChange = 0.90m, OtherInformation = "Merck & Co., Inc. is a leading global healthcare company that develops and manufactures innovative medicines, vaccines, and animal health products. Founded in 1891, Merck is known for its research-driven approach to advancing human and animal health. The company’s portfolio includes treatments for cancer, infectious diseases, and chronic conditions. Merck’s commitment to scientific excellence and improving global health has made it a trusted name in the pharmaceutical industry." }},
            { 44, new Stock { Id = 44, Name = "Costco Wholesale Corp. (COST)", Price = 463.55m, DailyChange = 2.12m, OtherInformation = "Costco Wholesale Corporation, founded in 1983, is one of the largest membership-only warehouse clubs in the world. The company offers a wide variety of goods, from groceries and electronics to apparel and furniture, all at discounted prices. Costco is known for its bulk sales, high-quality private-label products, and strong commitment to customer satisfaction. The company’s unique membership model, which includes annual fees, helps generate consistent revenue and build customer loyalty. Costco’s success is built on its efficient supply chain, dedicated workforce, and the value it provides to its members globally." }},
            { 45, new Stock { Id = 45, Name = "Johnson Controls International plc (JCI)", Price = 61.29m, DailyChange = -0.55m, OtherInformation = "Johnson Controls International plc is a global leader in building technologies and energy solutions. Founded in 1885, the company provides products and services that enhance building efficiency, sustainability, and safety. Johnson Controls’ offerings include HVAC equipment, fire and security systems, and building automation solutions. The company is committed to driving sustainability through energy-efficient technologies and smart building solutions. With operations in over 150 countries, Johnson Controls plays a crucial role in shaping the future of urban infrastructure and energy management." }},
            { 46, new Stock { Id = 46, Name = "Colgate-Palmolive Co. (CL)", Price = 74.12m, DailyChange = 0.43m, OtherInformation = "Colgate-Palmolive Company is a multinational consumer goods corporation, known for its oral care, personal care, home care, and pet nutrition products. Founded in 1806, Colgate-Palmolive has built a strong brand portfolio, with popular products like Colgate toothpaste, Palmolive dish soap, and Hill’s pet food. The company operates in over 200 countries and is committed to sustainability and social responsibility. Colgate-Palmolive’s focus on innovation and consumer trust has made it a global leader in the consumer goods industry." }},
            { 47, new Stock { Id = 47, Name = "Honeywell International Inc. (HON)", Price = 187.92m, DailyChange = 1.12m, OtherInformation = "Honeywell International Inc., founded in 1906, is a multinational conglomerate known for its diversified technology and manufacturing solutions. The company operates in four primary business segments: aerospace, building technologies, performance materials and technologies, and safety and productivity solutions. Honeywell’s products range from aircraft systems and building controls to advanced materials and automation equipment. The company’s focus on innovation, sustainability, and safety has made it a key player in various industries, including aerospace, industrial automation, and energy." }},
            { 48, new Stock { Id = 48, Name = "PayPal Holdings Inc. (PYPL)", Price = 92.34m, DailyChange = -0.82m, OtherInformation = "PayPal Holdings Inc. is a leading digital payments company, enabling individuals and businesses to make secure and convenient online transactions. Founded in 1998 and spun off from eBay in 2015, PayPal has grown into one of the most popular payment platforms globally. The company offers services such as person-to-person payments, online checkouts, and mobile payments through its app. With over 400 million active users, PayPal’s commitment to innovation, security, and financial inclusion has positioned it as a leader in the digital payments industry." }},
            { 49, new Stock { Id = 49, Name = "Union Pacific Corp. (UNP)", Price = 209.83m, DailyChange = -1.02m, OtherInformation = "Union Pacific Corporation is one of the largest railroad companies in the United States, providing transportation services across 23 states. Founded in 1862, Union Pacific has played a significant role in the development of America’s transportation infrastructure. The company transports a variety of goods, including agricultural products, chemicals, and intermodal freight. Union Pacific’s extensive rail network and commitment to safety and efficiency have positioned it as a key player in the logistics and transportation industry." }},
            { 50, new Stock { Id = 50, Name = "Amgen Inc. (AMGN)", Price = 230.44m, DailyChange = 1.34m, OtherInformation = "Amgen Inc. is a leading biopharmaceutical company, focused on discovering, developing, and delivering innovative human therapeutics. Founded in 1980, Amgen has built a strong portfolio of biologic and biosimilar medicines, particularly in the fields of oncology, cardiology, and inflammation. The company’s commitment to science and biotechnology has enabled it to develop life-saving treatments for patients around the world. Amgen’s focus on research and patient outcomes has positioned it as a leader in the biotechnology industry." }},
            { 51, new Stock { Id = 51, Name = "Schlumberger Ltd. (SLB)", Price = 48.22m, DailyChange = 0.67m, OtherInformation = "Schlumberger Ltd. is the world’s largest oilfield services company, providing technology, information solutions, and integrated project management to the oil and gas industry. Founded in 1926, Schlumberger operates in over 120 countries and offers a wide range of services, including exploration, drilling, and production. The company’s commitment to technological innovation and operational excellence has made it a key partner for energy companies seeking to optimize their exploration and production activities." }},
            { 52, new Stock { Id = 52, Name = "The Kraft Heinz Co. (KHC)", Price = 36.29m, DailyChange = 0.15m, OtherInformation = "The Kraft Heinz Company is one of the largest food and beverage companies in the world, known for its iconic brands such as Heinz ketchup, Kraft cheese, and Oscar Mayer meats. Formed through the merger of Kraft Foods and Heinz in 2015, the company operates in over 40 countries and offers a wide variety of products. Kraft Heinz is focused on product innovation, cost management, and sustainability initiatives to drive growth and meet changing consumer preferences." }},
            { 53, new Stock { Id = 53, Name = "The Charles Schwab Corp. (SCHW)", Price = 72.01m, DailyChange = 0.85m, OtherInformation = "The Charles Schwab Corporation is a leading provider of investment and financial services, founded in 1971 by Charles R. Schwab. The company offers a range of services, including brokerage, wealth management, banking, and retirement planning. Schwab’s focus on customer-centric solutions, low-cost investment options, and digital tools has made it a trusted name in the financial services industry. The company’s acquisition of TD Ameritrade has further expanded its market presence and client base." }}
        };

        // Set up a timer to simulate price changes every minute 
        _timer = new Timer(SimulatePriceChanges, null, TimeSpan.Zero, TimeSpan.FromSeconds(1)); 
    }

    // Simulate price changes for all stocks in-memory
    private void SimulatePriceChanges(object state)
    {
        foreach (var stock in _stockData.Values)
        {
            var oldPrice = stock.Price;

            // Stock price simulation
            decimal volatility = 0.02m; // Adjust for desired volatility
            decimal drift = 0.001m;     // Adjust for general market trend
            decimal randomFactor = (decimal)(_random.NextDouble() - 0.5); // Random factor between -0.5 and 0.5
            decimal priceChange = drift * oldPrice + volatility * oldPrice * randomFactor;

            stock.Price += priceChange;

            // Calculate the daily change percentage
            stock.DailyChange = Math.Round((priceChange / oldPrice) * 100, 2);

            // Ensure price doesn't go below zero
            if (stock.Price < 0) stock.Price = 0;

            // Invoke the StockUpdated event to notify about this specific stock update
            StockUpdated?.Invoke(stock);
        }

        // Notify any components that the prices have been updated
        OnPricesUpdated?.Invoke();
    }

    // Get all stock data (for tables like Trade, Portfolio, Watchlist)
    public List<Stock> GetAllStocks()
    {
        return _stockData.Values.ToList();
    }

    // Get a specific stock by ID
    public Stock GetStockById(int id)
    {
        return _stockData.ContainsKey(id) ? _stockData[id] : null;
    }
}

